# eureka.yml

spring:
  application:
    name: eureka
  cloud:
    config:
      override-none: true 
  rabbitmq:
    host: 192.168.64.140
    port: 5672
    username: admin
    password: admin
  
eureka:  instance:
    prefer-ip-address: true # 使用ip进行注册
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port} # 界面列表中显示的格式也显示ip
     